In [18]:
from bs4 import BeautifulSoup
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [19]:
#run this only once
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jen5en25\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from sklearn.datasets import fetch_20newsgroups
categories = ['rec.sport.baseball']
dataset = fetch_20newsgroups(subset='all',shuffle=True, random_state=42, categories=categories)
corpus = dataset.data

In [23]:
from sklearn.datasets import fetch_20newsgroups
corpus = dataset.data

In [24]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')
corpus = dataset.data

In [65]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')

from pprint import pprint
pprint(list(newsgroups_train.target_names))
['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [66]:
newsgroups_train.filenames.shape

(11314,)

In [67]:
newsgroups_train.target.shape

(11314,)

In [68]:
newsgroups_train.target[:10]

array([ 7,  4,  4,  1, 14, 16, 13,  3,  2,  4])

In [69]:
cats = ['alt.atheism', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)

In [70]:
list(newsgroups_train.target_names)

['alt.atheism', 'sci.space']

In [71]:
newsgroups_train.filenames.shape

(1073,)

In [72]:
newsgroups_train.target.shape

(1073,)

In [73]:
newsgroups_train.target[:10]

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [76]:
categories = ['alt.atheism', 'talk.religion.misc','comp.graphics', 'sci.space']

In [77]:
newsgroups_train = fetch_20newsgroups(subset='train',categories=categories)

In [78]:
vectorizer = TfidfVectorizer()

In [79]:
vectors = vectorizer.fit_transform(newsgroups_train.data)

In [80]:
vectors.shape

(2034, 34118)

In [81]:
vectors.nnz / float(vectors.shape[0])

159.0132743362832

In [1]:
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.datasets import fetch_20newsgroups
categories = ['rec.sport.baseball']
dataset = fetch_20newsgroups(subset='all',shuffle=True, random_state=42, categories=categories)
corpus = dataset.data

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jen5en25\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from pprint import pprint
pprint(list(dataset.target_names))

['rec.sport.baseball']


In [5]:
corpus[0]

"From: writingctr@leo.bsuvc.bsu.edu\nSubject: Re: CUB fever.\nOrganization: Ball State University, Muncie, In - Univ. Computing Svc's\nLines: 21\n\n\nIn article <kingoz.735285670@camelot>, kingoz@camelot.bradley.edu (Orin Roth) writes:\n> \n>    CUB fever is hitting me again. I'm beginning to think they have a \n>    chance this year. (what the heck am i thinking?)\n>    Sorry. Just a moment of incompetence.\n>    I'll be ok. Really. \n>    Orin.\n>    Bradley U.\n> \n> --\n> I'm really a jester in disguise!                                   \nI hear ya!  Then again, we must remember that we are indeed Cub fans, and\nthat the Cubs will eventually blow it.  After all, the Cubs are the easiest\nteam in the National League to root for.  No Pressure.  You know they will\nlose eventually.  Oh well, I suppose we must have faith.  After all, they\ndo look pretty good, and they don't even have Sandberg back yet.  \n\nCUBS IN '93!!!!!\n\nCHA\n"

In [6]:
corpus[2]

'From: steph@pegasus.cs.uiuc.edu (Dale Stephenson)\nSubject: "Seer" Stephenson picks the A.L. East\nSummary: The division has gone to the birds\nKeywords: last chance for foolishness\nArticle-I.D.: pegasus.steph.733989466\nOrganization: University of Illinois, Dept. of Comp. Sci., Urbana, IL\nLines: 95\n\nHaving run completely out of time, I\'ve got to get my prophesies and\npredictions for the A.L. out.  Qualifications -- one of the worse\nfinishes in last year\'s prediction contest.\n\nAL East -- 1993\n\n1.  Baltimore Orioles\nWhy the Orioles?  Well, I pondered long and hard, and it all came down to\nthis:\n  -- The Blue Jays are going the wrong direction.\n  -- Can\'t bring myself to pick the Yankees\n  -- Milwaukee was a fluke\n  -- Indians aren\'t ready to contend\n  -- Red Sox were bad last year, and didn\'t get any better\n  -- Detroit\'s pitching will be the new definition of "replacement level"\n"But you don\'t really think the Orioles will win, do you."  No.  As a matter\nof 

In [7]:
stopset = set(stopwords.words('english'))
stopset.update(['lt','p','/p','br','amp','quot','field','font','normal','span','0px','rgb','style','51', 
                'spacing','text','helvetica','size','family', 'space', 'arial', 'height', 'indent', 'letter'
                'line','none','sans','serif','transform','line','variant','weight','times', 'new','strong', 'video', 'title'
                'white','word','letter', 'roman','0pt','16','color','12','14','21', 'neue', 'apple', 'class', '\n', '@', '00', '00 00',
               'nntp', 'edu', 'cs','com','000','etc', 'john', 'morris', 'mjones', 'jones','kingman', 'jack','dave','williams', 'ted', 'duke', 'hirschbeck', 'asd'
               ,'01','02','03','04','05', '06', '07', '08', '09', '10','vb30','samuel','torre', 'scott', 'barman','smith','steve'
                ,'gant','hall','david', 'sabo', 'aix','clemens','lopez','roger','viola','mike', 'joe', 'jays','braves','fischer','sherri','sreph','mark','nichols',
               'dale','stehpenson','michael','lowenstein' 'barry', 'aaa','alomar','boggs','pitt','greg','bob','000th','001','0010','edward'])

In [8]:
vectorizer = TfidfVectorizer(stop_words=stopset,
                                 use_idf=True, ngram_range=(1, 3))
X = vectorizer.fit_transform(corpus)

In [9]:
X[0]

<1x182857 sparse matrix of type '<class 'numpy.float64'>'
	with 224 stored elements in Compressed Sparse Row format>

In [11]:
print (X[0])

  (0, 49037)	0.0742564870498
  (0, 182122)	0.0742564870498
  (0, 27423)	0.0742564870498
  (0, 139857)	0.0742564870498
  (0, 59877)	0.0742564870498
  (0, 73251)	0.0742564870498
  (0, 127244)	0.0742564870498
  (0, 97887)	0.0742564870498
  (0, 62265)	0.0742564870498
  (0, 108452)	0.0742564870498
  (0, 156476)	0.0742564870498
  (0, 174240)	0.0742564870498
  (0, 113619)	0.0742564870498
  (0, 60021)	0.0742564870498
  (0, 98266)	0.0742564870498
  (0, 90175)	0.0742564870498
  (0, 127159)	0.0742564870498
  (0, 137129)	0.0742564870498
  (0, 92799)	0.0742564870498
  (0, 109093)	0.0742564870498
  (0, 158862)	0.0742564870498
  (0, 56625)	0.0742564870498
  (0, 49075)	0.0742564870498
  (0, 34245)	0.0742564870498
  (0, 60007)	0.0742564870498
  :	:
  (0, 79722)	0.0346012202208
  (0, 178644)	0.0157174658139
  (0, 137376)	0.0558019478487
  (0, 116302)	0.111603895697
  (0, 35888)	0.100076174847
  (0, 38795)	0.105677832323
  (0, 15195)	0.0742564870498
  (0, 89561)	0.111603895697
  (0, 24218)	0.016256839015

In [12]:
X.shape

(994, 182857)

In [13]:
lsa = TruncatedSVD(n_components=150, n_iter=100)
lsa.fit(X)

TruncatedSVD(algorithm='randomized', n_components=150, n_iter=100,
       random_state=None, tol=0.0)

In [14]:
lsa.components_[0]

array([ 0.00055237,  0.00055237,  0.00055237, ...,  0.0011523 ,
        0.0011523 ,  0.0011523 ])

In [15]:
import sys
print (sys.version)

3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]


In [16]:
terms = vectorizer.get_feature_names()
for i, comp in enumerate(lsa.components_): 
    termsInComp = zip (terms,comp)
    sortedTerms =  sorted(termsInComp, key=lambda x: x[1], reverse=True) [:10]
    print("Concept %d:" % i )
    for term in sortedTerms:
        print(term[0])
    print (" ")

Concept 0:
year
team
would
game
writes
article
baseball
players
games
one
 
Concept 1:
jewish
lafayette
lafibm
baseball players
come
jewish baseball
jewish baseball players
lafibm lafayette
sandy koufax
players
 
Concept 2:
lost
idle
red sox
san
phillies
west
home
american
baltimore
play
 
Concept 3:
clutch
performance
lost
netcom
hit
non clutch
year
situations
future
mss
 
Concept 4:
ibm
kingston
pitcher
era
winning
world
say
lot
toronto
games
 
Concept 5:
maybe
games
average
pitch
steph
game
two
every
score
past
 
Concept 6:
bonds
batting
ibm
may
giants
behind
good
stanford
kingston
hitter
 
Concept 7:
mets
good
average
jewish
uiuc
pretty
third
players
steph
15
 
Concept 8:
princeton
clutch
fans
still
winfield
well
distribution
fame
people
go
 
Concept 9:
cubs
team
said
day
world
could
university
colorado
america
base
 
Concept 10:
team
runs
might
rose
player
rickert
hulman
rose hulman
since
jhunix
 
Concept 11:
ibm
kingston
ca
uiuc
best
sox
world
rbi
win
sure
 
Concept 12:
well
news

In [17]:
lsa.components_

array([[  5.52366754e-04,   5.52366754e-04,   5.52366754e-04, ...,
          1.15229615e-03,   1.15229615e-03,   1.15229615e-03],
       [ -1.78109372e-03,  -1.94025381e-03,   1.62894070e-02, ...,
          5.04057409e-04,   5.04057409e-04,   5.04057409e-04],
       [  3.88084659e-05,   1.37970700e-03,   1.00019602e-02, ...,
          1.83011375e-03,   1.83011375e-03,   1.83011375e-03],
       ..., 
       [ -2.36660116e-02,  -3.00020505e-02,  -2.56141857e-01, ...,
         -4.74413597e-04,  -4.74413597e-04,  -4.74413597e-04],
       [  2.39157299e-02,   1.64552638e-02,   1.88803269e-01, ...,
          9.16390072e-04,   9.16390072e-04,   9.16390072e-04],
       [ -1.14506025e-02,  -1.28224934e-02,  -3.48169212e-01, ...,
          2.00558583e-04,   2.00558583e-04,   2.00558583e-04]])